### ISSUE TITLE
Root transitions in local frames

### ISSUE THREAD

**Issue by vmpstr** [WICG/view-transitions#1]
The API dictates that the transition is based on the document. If we have a local frame with its own document, then presumably we should be able to root-transition it independently of the top level document.

We need to add some examples of this. Also, examples where the root and the local frame root-transition at the same time.

**Comment by khushalsagar** [comment]
This sounds like a feature request to support document transitions for iframes. It's doable but I don't think we can prioritize it for the first iteration of the feature.

**Comment by vmpstr** [comment]
I suspect it's an important case for widgets being same origin iframes. But we should at least ensure that it doesn't break: if a frame on my page is using this animation, I don't want the root of _my_ page to all of a sudden slide around

**Comment by colepeters** [comment]
Just wondering if there's been further discussion on this issue? I'm currently trying out view transitions on an app which uses iframes. I get the view transitions I expect when navigating between 2 pages, but navigating through those pages within an iframe produces no view transition. I'm guessing that's expected given the conversation here? And if so, are there any thoughts on how to address this? :)

**Comment by khushalsagar** [comment]
Thanks for bringing this up! You're right that this should work for navigations within an iframe. The feature is still a WIP in chromium and iframe support hasn't landed yet. I just filed a [bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1481881) to track it. Feel free to star it to keep tab on when this lands.

**Comment by colepeters** [comment]
@khushalsagar Rad, thank you!
