### ISSUE TITLE
Handling changes in large viewport size.

### ISSUE THREAD

**Issue by jakearchibald** [WICG/view-transitions#13]
What should happen if the window size changes mid-transition? Aborting the transition animation seems reasonable in this case. It's unclear whether that should show up in the API as an AbortError.

**Comment by khushalsagar** [comment]
Yeah, I think the conclusion of the last discussion was that we should abort the transition (directly jump to the final state) if the viewport size changes between prepare and all animations associated with a transition finishing.

I don't think this needs to raise an error in the API. It would trigger the transitionEnd event sooner than if the transition would've finished though.

**Comment by khushalsagar** [comment]
We're going to gracefully handle cases where the layout or visual viewport changes by snapshoting the [large viewport](https://drafts.csswg.org/css-values-4/#large-viewport-size). But in case the large viewport itself changes (like the window resize), aborting makes sense.

Gonna close this once its added to the spec.
