### ISSUE TITLE
Gesture linked view transitions

### ISSUE THREAD

**Issue by pavsidhu** [WICG/view-transitions#199]
I noticed that there is no way to link a gesture to an animation - a common practice in native apps, [especially in material design](https://m2.material.io/design/interaction/gestures.html#types-of-gestures). Is this something that has purposefully not been considered for this proposal?

**Comment by jakearchibald** [comment]
It's not something we're looking at for the first release, but it's something we can look at in future. Some similar discussion: https://github.com/WICG/view-transitions/issues/146

**Comment by pavsidhu** [comment]
Ahh awesome, thanks for letting me know!

**Comment by jakearchibald** [comment]
See also https://twitter.com/jaffathecake/status/1595811562614558720
