### ISSUE TITLE
Link to spec prominently

### ISSUE THREAD

**Issue by foolip** [WICG/view-transitions#201]
It took me some time to find https://drafts.csswg.org/css-view-transitions-1/ from this repo.

**Comment by jakearchibald** [comment]
Good point. I've added a link to the description of the repo.

**Comment by foolip** [comment]
Perfect, that's the first place I always look :)

**Comment by jakearchibald** [comment]
It's a bit confusing that we have stuff split between here and the CSSWG right now, but I'm happy to just deal with issues being filed in either place right now, since I think this place is more discoverable, but the CSSWG is more official. I can move issues if needed.
