### ISSUE TITLE
Customising Cross Document Transitions 

### ISSUE THREAD

**Issue by domchristie** [WICG/view-transitions#212]
I'm really enjoying playing around the JavaScript API so far!

When it comes to cross document transitions, are there any plans to tackle the approach detailed in Google's guide, whereby [multiple element can share the same `view-transition-name` if it's added dynamically](https://developer.chrome.com/docs/web-platform/view-transitions/#transitioning-elements-dont-need-to-be-the-same-dom-element)?

Currently, if I wish to achieve the same transition without JS, I'd have to give each thumbnail its own unique `view-transition-name`, making it difficult to customise the transition with CSS i.e. I'd have to write `::view-transition-old(image-123)`/`::view-transition-new(image-123)` selectors for every image.

Given the following HTML, are there any plans to support something like wildcard selectors for the view transition pseudo elements, e.g. `::view-transition-old(image-*)`?

```html
<img src="http://example.com/image-1.jpg" style="view-transition-name: image-123"/>
<img src="http://example.com/image-2.jpg" style="view-transition-name: image-456"/>
```

**Comment by jakearchibald** [comment]
Does https://github.com/w3c/csswg-drafts/issues/8319 cover your use-case?

**Comment by domchristie** [comment]
@jakearchibald yes!
