### ISSUE TITLE
Better error message for passing in incorrect parameter to startViewTransition?

### ISSUE THREAD

**Issue by Darkle** [WICG/view-transitions#218]
Hi, I had the following incorrect code:

```js
let foo = () => {}
document.startViewTransition(foo())
```
which produced an error message of: `TypeError: Failed to execute 'startViewTransition' on 'Document': Overload resolution failed.`

My mistake of course was that the second line should instead be:
```js
document.startViewTransition(foo)
```
However it took me a while to figure this out as I found the error message to be a bit confusing. Could it be improved a little? Maybe add a "startViewTransition expects a function" or something?

Cheers.

**Comment by vmpstr** [comment]
Thank you for the suggestion. Unfortunately this is outside of our control. I believe this error message would be from bindings or something similar. I'm going to close as not actionable (by us)
