### ISSUE TITLE
Allow transitions on a DOM sub-tree.

### ISSUE THREAD

**Issue by jakearchibald** [WICG/view-transitions#32]
Take a layout like this: https://static-misc-3.glitch.me/document-transition-demo/contained.html

It seems like the current API doesn't cater for this, where I want the transition to be limited to within the chat messages element, as if it were its own viewport.

I guess I could do it with an iframe, but that seems unnecessary.

**Comment by chrishtr** [comment]
> It seems like the current API doesn't cater for this

Because MPA transitions are always on the whole document? Are you looking for a non-root MPA transition?

**Comment by khushalsagar** [comment]
This seems like a valid use-case for both SPA/MPA. Basically you want an animation limited to shared elements because the root content is the same on both pages. We could have a "none" root transition type which displays the dest root content at the beginning of the transition with no animation.

**Comment by jakearchibald** [comment]
Ugh, sorry, the title said MPA when I meant SPA. That wasn't very helpful 😀

Yeah, I mean non-root transitions. Maybe there's a car for this with MPA too, but it's more likely with SPA.

**Comment by chrishtr** [comment]
Oh ok. I agree that non-root transitions are needed. Vlad had it on his backlog, and we'll need to adjust the API shape accordingly.

**Comment by jeremyroman** [comment]
There is a "none" transition type in the implementation, used if the `rootTransition` key isn't present in the options. @khushalsagar does this not do what you describe?

**Comment by jakearchibald** [comment]
I guess if you could provide an outgoing & incoming transform for shared elements, that would be enough. But right now there's no way to do, say, "cover-left" on a shared element.

**Comment by domenic** [comment]
This would make my demo site at https://gigantic-honored-octagon.glitch.me/subpage.html nicer. Only the contents inside the dashed border are supposed to change, but right now the whole page does the transition.

I might be able to make it work by marking up everything outside of that box as a shared element?

**Comment by khushalsagar** [comment]
Yeah, that should work. Anything you make a shared element which has the same content before/after the transition will draw like a static image on top while the background underneath does the transition.

**Comment by khushalsagar** [comment]
The feature request brought up here is already covered in #37 (having entry/exit animations for non-root elements) and #28 (enabling customization with an outgoing/incoming transform instead of high level patterns).

But your comment above makes it sound like you also want clipping : "...as if it were its own viewport". So in the [example](https://static-misc-3.glitch.me/document-transition-demo/contained.html), you might want the content of "messages" to be clipped by the container instead of drawing on top of "people"/"header" as it translates during the transition?

**Comment by hvanops** [comment]
Duplicated in https://github.com/WICG/view-transitions/issues/52
