### ISSUE TITLE
Providing entry/exit animations for elements that only exist on one page

### ISSUE THREAD

**Issue by rcourtie** [WICG/view-transitions#37]
A feature that would be good to include is to allow setting entry/exit animations for elements that only exist on one of the pages. For example having a page footer slide off screen:

![entry-exit-animations](https://user-images.githubusercontent.com/163378/124840769-94116100-df40-11eb-906c-e62f0767461d.png)

One way it could be done is for elements that are entering or exiting is to specify them in the `sharedElement` options, but have the corresponding element be `null`.

It would also require some way to specify the transform for the incoming/outgoing element. Below is a suggestion with an array of the transition types, and it uses the same corresponding API the sharedElements currently uses.

```javascript
function handleTransition() {
  document.documentTransition.prepare({
    rootTransition: "reveal-left",
    // e1 here would be the footer, and it would get an exit animation since the sharedElements
    // option below at the same index is `null`
    sharedElements: [e1, e2, e3],
    sharedTransitions: ["slide-down", undefined, undefined],
  }).then(() => {
    changeBodyBackground();
    document.documentTransition.start({ sharedElements: [null, newE2, newE3] }).then(
      () => console.log("transition finished"));
  });
}
```

This is also one way to handle #34

**Comment by khushalsagar** [comment]
Another use-case that I'm assuming you'd hit here is doing these transitions within a particular element, similar to what was pointed in #32 . So the footer is optionally clipped by a container as it slides down.
