### ISSUE TITLE
Ensure transitions API integrates well with app-history

### ISSUE THREAD

**Issue by uasan** [WICG/view-transitions#39]
Hello.
It looks like we have two different interfaces to achieve the same goals in the SPA, is that how it was conceived?
https://github.com/WICG/app-history#example-async-transitions-with-special-backforward-handling

**Comment by domenic** [comment]
I think they're very much complementary :). See the demo at https://gigantic-honored-octagon.glitch.me/subpage.html which shows how app history, which lets you have a single `navigate` handler to perform all your SPA navs, with shared element transitions. You add two lines of code inside that `navigate` handler and now all your SPA navs are using transitions!!

**Comment by uasan** [comment]
Yes, you are right, you need to find some free time and make  demo of the interaction of the three new interfaces:

1. shared-element-transition
2. [appHistory](https://github.com/WICG/app-history)
3. [URLPattern](https://github.com/WICG/urlpattern/blob/main/mdn-drafts/QUICK-REFERENCE.md)

**Comment by khushalsagar** [comment]
Thanks for bringing this up. We should keep this in mind as we think through the MPA API for this.
