### ISSUE TITLE
Previous work: "layout transitions"

### ISSUE THREAD

**Issue by tabatkins** [WICG/view-transitions#40]
Several years back, Shane Stephens and I explored this exact same space, and came up with a draft <https://tabatkins.github.io/specs/layout-transitions/>.

Filing this just to have a record we can explore of previous attempts in this space.

/cc @chrishtr

**Comment by chrishtr** [comment]
@khushalsagar @ianvollick @jakearchibald  ^^^

This even has the concept of a "ghost element" for stuff not in DOM because it's being transitioned, in the form of I think a pseudo element.

**Comment by jakearchibald** [comment]
Oh nice! I wasn't aware of this. This has similarities to the DOM-to-canvas idea in https://github.com/WICG/shared-element-transitions/issues/15 I think.

@khushalsagar's latest proposal has similarities too, but allows the idea to work across documents.

Cross-fading is starting to look like a really tricky part of this. We'll want proper cross-fading of textures, but CSS `cross-fade()` forces all given images into the same size, which we don't really want.

For instance, if the heading "Interesting article" is transitioning into "Interesting article: more details" (and it has a max-content width), then the developer will probably want the textures to remain their natural size, and be positioned at eachother's top-left. However, there are a bunch of other cases where you want different positioning and scaling. Feels like we still need object-fit/position style features here.

Going via `element()` is okay, but it loses anything outside the element's bounds. I think the 'proper' solution will give you the full texture, along with the bounding rect relative to the texture.

**Comment by tabatkins** [comment]
> CSS cross-fade() forces all given images into the same size

It doesn't; the resulting image transitions its size between the source image sizes at the same time.

That said, an earlier version of this idea had a pseudo-element being created during the transition, which had access to the start and end textures as CSS images and could do whatever it wanted with them. That's a way more general solution, but it requires capturing start/end states more explicitly, which I *think* the current spec accomplishes?

> Going via element() is okay

Yeah, and that particular API kinda died anyway; we can do whatever's necessary.

**Comment by jakearchibald** [comment]
> It doesn't; the resulting image transitions its size between the source image sizes at the same time.

Ohhhh, I misread the spec, cheers! But still, that's a behaviour we won't want in many situations.
