### ISSUE TITLE
Update read me file consistent with the resolution of issue #19 concerning prefers-reduced-motion

### ISSUE THREAD

**Issue by CharlesBelov** [WICG/view-transitions#45]
[Issue #19 Automatically disabling animations in prefers-reduced-motion mode](https://github.com/WICG/shared-element-transitions/issues/19) discusses automatic handling of user prefers-reduced-motion as part of this implementation.

If issue #19 is not implemented, then it would be best if the [Read Me file for shared element transitions](https://github.com/WICG/shared-element-transitions#readme) includes instructions and sample code for respecting prefers-reduced-motion with respect to shared element transitions.

If issues #19 is implemented, then it would be best if the Read Me file documents how prefers-reduced-motion is being supported within shared element transitions.

**Comment by hvanops** [comment]
Article specifies prefers-reduced-motion https://developer.chrome.com/docs/web-platform/view-transitions/#reacting-to-the-reduced-motion-preference
