### ISSUE TITLE
Transition in AMP pages

### ISSUE THREAD

**Issue by svdoever** [WICG/view-transitions#54]
Would there be a possibility to apply these transitions to AMP pages as well? Would be great if it could be implemented using an attribute model, instead of using <amp-script /> to call the transitions API.

**Comment by khushalsagar** [comment]
Could you clarify the feature request more? I'm not well versed with the limitations for AMP pages. Also I'm assuming this is for cross-document transitions (MPA) and not same document transitions (SPA).

**Comment by khushalsagar** [comment]
Some ongoing discussion about this is in #59 and #61.

**Comment by khushalsagar** [comment]
One thing I want to highlight is that it should be very feasible to do a root transition in this case. You can set up an animation on the root element of the outgoing page and on the iframe element on the incoming page. Doing shared element transitions referencing elements within the iframe's Document will need work.
